### ISSUE TITLE
[Bug] Shadow

### ISSUE THREAD

**Issue by CrimeMoot** [Rxup/space-station-14#768]
### Описание

Раса сумеречников не дышат и не обладают данной функции.
Но, при всём при этом - они испытывают **удушение** и проигрывают **задыхается**

### Шаги воспроизведения

1. Зайти в игру
2. Взять расу сумеречников
3. Убрать весь воздух, можно выйти в космос.
4. Задыхаемся - когда сумеречники не дышат.

**Comment by PuroSlavKing** [comment]
а где написано, что они не дышат?

**Comment by CrimeMoot** [comment]
Зайди в любую разгерму
Там эмоут будет **задыхается**
Хотя они урон от удушья не получают. Т.к не дышат.

**Comment by PuroSlavKing** [comment]
так ээ, почему они не дышат, чем это обусловлено, я не сомневался, что это сомнительная раса, но чтоб настолько. Тут уже стоит вопрос о том, чтоб научить их дышать.

**Comment by CrimeMoot** [comment]
# ДА БРАТ ОНИ НЕ ДЫШАТ

**Comment by CrimeMoot** [comment]
Они никогда не дышали. Но почему-то никто не стал убирать отдышку из-за нехватки воздуха. А в крите они вообще могут всю смену пролежать. Т.к не получают удушение.

**Comment by PuroSlavKing** [comment]
> # ДА БРАТ ОНИ НЕ ДЫШАТ

"источник: поверь мне брат"?

**Comment by CrimeMoot** [comment]
Даже не пытайся на вики найти - там всё равно инфы 0.

**Comment by PuroSlavKing** [comment]
> > "источник: поверь мне брат"?
> 
> Ну зайди - проверь. Я лично на бекман пришёл месяц назад. До меня сумеречник был уже на протяжении года. И всегда не дышал. Это не ко мне вопросы.

Да какая разница что там в механе, если он не обоснован ничем, даже гибриды ксеноморфа не имеют иммунитета к удушью

**Comment by CrimeMoot** [comment]
> Да какая разница что там в механе, если он не обоснован ничем, даже гибриды ксеноморфа не имеют иммунитета к удушью

Тогда это всё ещё не отменяет Баг.
Они не дышат, проигрывается эмоут **задыхается**
Они дышат? Не получают урон от удушение.

Так что всё равно баг. Либо вернуть чтоб дышали, либо убрать эмоут **задыхается**

**Comment by PuroSlavKing** [comment]
Вердикт:
### Будут дышать.
