### ISSUE TITLE
Surgery Playtest Issues

### ISSUE THREAD

**Issue by Roudenn** [Rxup/space-station-14#873]
## [RU]
Это сборник самых критических багов в системе новой Хирургии. Они планируются к исправлению на стороне нашего билда, и затем могут быть портированы на основной ПР от Einstein Engines.
## [EN]
This  issue contains most of the critical bugs of the Surgery system. We are planning to fix all of those on our build, and then can be ported back on the main Surgery PR by Einstein Engines.

Related to https://github.com/Simple-Station/Einstein-Engines/pull/1159 (EE)
And https://github.com/Rxup/space-station-14/pull/868 (Backmen)

## Verified issues [EN]:
- [x] Any non-standard damage to the player will end up on the Left Leg specifically (explosions or anyone who don't have doll limbs targeting)
- [x] There is no way to see what limbs are damaged specifically from aside (would be good to have the doll in Healh Analyzer)
- [x] Doll damage & Entity damage aren't syncronised properly (It will only heal if you target the damaged limb specifically, and if there's a damaged limb and total damage is 0 it will just infinitly waste medicals) (Probably it should automaticly target the healing to the most damaged limb)
- [ ] ~~There is no easy way to see what is messed up inside patient's body (missing organs, damaged bones, ect.)~~ Actually there's no things for now that can be broken like stated there...
- [x] Debug Heal doesn't heal any organs
- [x] You can make surgery on yourself (something you shouldn't normally do, at least without training)
- [ ] When detaching (or attaching in specific cases) Incisions are automaticly closed, even tho they should be opened since you didn't closed them.

## Известные проблемы [RU]
- [x] Любой нестандартный урон игроку будет попадать именно в левую ногу (взрывы или противники, которые не целятся в куклу).
- [x] Нет возможности увидеть, какие конечности повреждены конкретно со стороны (было бы хорошо иметь отображение куклы в анализаторе здоровья).
- [x] Урон кукле и урон сущности не синхронизированы должным образом (исцеление происходит только при прицеливании в повреждённую конечность, и если есть повреждённая конечность, а общий урон равен 0, медикаменты будут тратиться бесконечно впустую). (Вероятно, лечение должно автоматически нацеливаться на наиболее повреждённую конечность).
- [ ] ~~Нет простого способа увидеть, что именно нарушено внутри тела пациента (отсутствующие органы, повреждённые кости и т. д.).~~ Оказывается пока что нету таких частей которые могут быть сломаны при помощи хирургии...
- [x] Дебаг Лечение не лечит органы
- [x] Можно оперировать самого себя (что-то чего обычно быть не должно, по крайней мере без подготовки)
- [ ] Во время удаления (или пришивания в определённых случаях) конечностей, разрезы автоматически закрываются, даже не смотря на то что они не были ни кем закрыты.

**Comment by TokenStyle** [comment]
also known bugs:
```
- [ ] You can't get out the item that you putted in somebody's torso (for example, nuclear disk you put inside captain, and you can't get it back). The button that lets you retrieve the item never becomes clickable.
```
The reason is `Content.Shared\Backmen\Surgery\SharedSurgerySystem.Steps.cs` the `partComp.ItemInsertionSlot.HasItem` is always false

**Comment by Roudenn** [comment]
> also known bugs:
> 
> ```
> - [ ] You can't get out the item that you putted in somebody's torso (for example, nuclear disk you put inside captain, and you can't get it back). The button that lets you retrieve the item never becomes clickable.
> ```
> 
> The reason is `Content.Shared\Backmen\Surgery\SharedSurgerySystem.Steps.cs` the `partComp.ItemInsertionSlot.HasItem` is always false

It should have been fixed by #875
